export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const DESELECT_CATEGORY = "DESELECT_CATEGORY";
export const CHANGE_CANPROGRESS = "CHANGE_CANPROGRESS";
export const GO_FORWARD = "GO_FORWARD";
